title: Jiahao Li
name: "Jiahao Li's Blog"
author: Jiahao Li
baseurl: "/"
permalink: /:title
show_drafts: false
future: false
category: "post"
img: ""
google_analytics: G-9BVSS0QW8P

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-twitter-plugin
exclude:
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
sass:
  sass_dir: _sass
